export const SET_LEVEL = 'SET_LEVEL'
export const ADD_ITEM = 'ADD_ITEM'
export const SET_CHECKED = 'SET_CHECKED'
export const SET_TEXT = 'SET_TEXT'
export const SET_INDEX = 'SET_INDEX'
export const GET_TODO = 'GET_TODO'
export const DELETE_ITEM = 'DELETE_ITEM'